import type { Metadata } from "next";

import "./globals.css";
import CampaignsPageProvider from "./context/campaignsPageProvider";

/**
 * Metadata for the application
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Digital Signage Manager",
  description: "Generated by create next app",
};

/**
 * 
 * @param {object} props
 * @param {React.ReactNode} props.children
 * @returns {JSX.Element}
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <CampaignsPageProvider>
      <html lang="es" suppressHydrationWarning>
        <body className="flex flex-col items-center">
          <main className="w-full max-w-5xl">
          {children}
          </main>
        </body>
      </html>
    </CampaignsPageProvider>
  );
}
