import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "Digital Signage Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className="flex flex-col items-center">
        <header className="w-full font-bold bg-red-700 text-white p-4">
          <Link href="/" className="text-xl">Digital Signage Manager</Link>
        </header> 
        <main className="w-full max-w-5xl">
        {children}
        </main>
      </body>
    </html>
  );
}
